rem start "title" "C:\Program Files\Freeplane\freeplane.exe"
start "mail" "C:\Program Files (x86)\Microsoft Office\Office15\OUTLOOK.exe"
start "Skype" "C:\Program Files (x86)\Microsoft Office\Office15\lync.exe"
start "web" "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
start "chrome" "C:\Users\mwroberts\AppData\Local\Google\Chrome\Application\chrome.exe"
start "bats" "C:\Windows\explorer.exe" "C:\Users\mwroberts\Desktop\bats"
start "evernote" "C:\Program Files (x86)\Evernote\Evernote\Evernote.exe"
start "OneNote" "C:\Program Files (x86)\Microsoft Office\Office15\onenote.exe"
rem start "webcam" "c:\Users\mwroberts\Desktop\portable-webcam.exe"
