#!/bin/bash
# file generated by turmoil.sh
#turmoil.sh -u ilya.usvyatsky -d 365 -o ${HOME}
###
FL='2012_04_04'
OUT='~/bin/data/vdsi/turmoil.html'
echo -e '<html>/n<body>\n' > ${OUT}
awk '$1 ~ /M/ {s="<a href=https://svn01.atlanta.hp.com/local/swd-usd-eng"
        printf("%s%s>%s</a><br>\n",s,$2,$2)}' ${FL}|
sort -u >> ${OUT}
echo -e '</body>/n</html>\n' >> ${OUT}
